[package]
name = "greenmail-reproduce"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
imap = "2.4.1"
lettre = "0.11.3"
native-tls = "0.2.11"
